arm_mount_on_base:
  position: {x: 0.0, y: 0.0, z: 0.18}
  rotation: {r: 0.0, p: 0.0, y: 0.0}
tcp_offset:
  position: {x: 0.0, y: 0.0, z: 0.0}
  rotation: {r: 0.0, p: 0.0, y: 0.0}
lidar_mount_on_base:
  position: {x: 0.25, y: 0.0, z: 0.35}
  rotation: {r: 0.0, p: 0.0, y: 0.0}
