/piper/controller_manager:
  ros__parameters:
    update_rate: 200

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/piper/arm_controller:
  ros__parameters:
    allow_nonzero_velocity_at_trajectory_end: false
    joints:
      - piper_joint1
      - piper_joint2
      - piper_joint3
      - piper_joint4
      - piper_joint5
      - piper_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
